# Interactive component

**Proportions of Patient Hospital Stay Lengths by Number of Previous Hospital Admissions**
  
Toggle between different numbers of previous hospital admissions using the button below to see how this affects the proportion of patient hospital stay lengths.


<html lang="en">
<meta charset="utf-8">

<!-- Load d3.js -->
<script src="https://d3js.org/d3.v7.js"></script>

<!-- Initialize a select button -->
<select id="selectButton"></select>

<!-- Create a div where the graph will take place -->
<div id="my_dataviz"></div>

<script>

// set the dimensions and margins of the graph
const margin = {top: 10, right: 100, bottom: 50, left: 30},
    width = 800 - margin.left - margin.right,
    height = 500 - margin.top - margin.bottom;
    

// append the svg object to the body of the page
const svg = d3.select("#my_dataviz")
  .append("svg")
    .attr("width", width + margin.left + margin.right)
    .attr("height", height + margin.top + margin.bottom)
  .append("g")
    .attr("transform",`translate(${margin.left}, ${margin.top})`);

//Read the data
d3.csv("https://raw.githubusercontent.com/Raphaeladda/LengthOfStay/main/initial/data_interactive.csv").then(function(data){

    // List of groups (here I have one group per column)
    const allGroup = ["zero","one","two","three","four","five_or_more"]

    // add the options to the button
    d3.select("#selectButton")
      .selectAll('myOptions')
     	.data(allGroup)
      .enter()
    	.append('option')
      .text(function (d) { return d; }) // text showed in the menu
      .attr("value", function (d) { return d; }) // corresponding value returned by the button

    // Add X axis --> it is a date format
    const x = d3.scaleLinear()
      .domain([1,9])
      .range([ 0, width ]);
    svg.append("g")
      .attr("transform", "translate(0," + height + ")")
      .call(d3.axisBottom(x));

    // Add Y axis
    const y = d3.scaleLinear()
      .domain( [0,100])
      .range([ height, 0 ])

    svg.append("g")
      .call(d3.axisLeft(y));

    // Initialize line with group a
    const line = svg
      .append('g')
      .append("path")
        .datum(data)
        .attr("d", d3.line()
          .x(function(d) { return x(+d.LoS) })
          .y(function(d) { return y(+d.zero) })
        )
        .attr("stroke", "black")
        .style("stroke-width", 4)
        .style("fill", "none")

    // Initialize dots with group a
    const dot = svg
      .selectAll('circle')
      .data(data)
      .enter()
      .append('circle')
        .attr("cx", function(d) { return x(+d.LoS) })
        .attr("cy", function(d) { return y(+d.zero) })
        .attr("r", 7)
        .style("fill", "#69b3a2")
      
    // Add the text label for the x axis
    svg.append("text")
      .attr("transform", "translate(" + (width) + " ," + (height + 0.7*margin.bottom) + ")")
      .style("text-anchor", "middle")
      .text("Length Of Stay (Days)");

    // Add the text label for the y axis
    svg.append("text")
      .attr("transform", "translate(" + (3*margin.left) + " ," + (margin.top) + ")")
      .style("text-anchor", "middle")
      .text("Percentage of Patients");


    // A function that update the chart
    function update(selectedGroup) {

      // Create new data with the selection?
      const dataFilter = data.map(function(d){return {LoS: d.LoS, value:d[selectedGroup]} })

      // Give these new data to update line
      line
          .datum(dataFilter)
          .transition()
          .duration(1000)
          .attr("d", d3.line()
            .x(function(d) { return x(+d.LoS) })
            .y(function(d) { return y(+d.value) })
          )
      dot
        .data(dataFilter)
        .transition()
        .duration(1000)
          .attr("cx", function(d) { return x(+d.LoS) })
          .attr("cy", function(d) { return y(+d.value) })
    }

    // When the button is changed, run the updateChart function
    d3.select("#selectButton").on("change", function(d) {
        // recover the option that has been chosen
        const selectedOption = d3.select(this).property("value")
        // run the updateChart function with this selected option
        update(selectedOption)
    })


})


</script>
</html>

## Interpretation:

This interactive connected scatterplot shows interesting patterns between the length of stay of a patient and the number of previous admissions. As expected, the length of a patient's stay in the hospital generally increases as the number of previous hospital admissions increases.

As is visible from switching through the different plots, you can see there is a striking difference between the plots of patients who had only zero or one previous admission(s) and the plots of patients who had more admissions. In the plots of patients who had only zero or one previous admissions(s), the majority of patients stayed for only a few days (1-3). Interestingly, all patients who stayed for only 1 day in the hospital had zero previous admissions. However, as you toggle the button onto plots of patients who had higher numbers of previous admissions to the hospital, you can see that the dots representing proportions of patients drop to zero one-by-one.

Effectively, the area under the curve becomes higher towards the right of the graph when we select high values of previous admissions, showing that patient stay lengths generally increase as the number of previous admissions increase. Thus we can conclude that the number of previous admissions is a useful indicator to estimate the length of stay of a patient in the hospital.

