# Conclusion

In conclusion, from this MIMIC-III Length of Stay dataset, we have learned various things about what may reasonably predict an incoming patient's length of stay in the hospital. Hopefully, these results may aid hospital management in more efficiently scheduling hospital staff and allocating resources. 

Some of the main takeaways are that, the majority of patients will stay only a few (1-4) days, although there may be some who stay for much longer (up to 13 days). Extreme physiological measurements, especially for the hematocrit, blood urea nitrogen, and respiration categories, may indicate that a patient may be staying for longer than the average patient. However, this does not preclude patients with average hematocrit or blood urea nitrogen levels from staying for long periods of time. The project also found that patients with more pre-existing medical conditions had longer stays, whilst many patients with fewer or no pre-existing medical conditions stayed for only a couple of days. Patients who had a higher number of previous hospital visits in the past 180 days also generally had longer stays. 

One of the main limitations – something we were not able to explore with this dataset – was how physiological data changed throughout a patient’s course of stay. The physiological data provided was the average values of a patient’s measurements over their entire length of stay at the hospital, not individual day-by-day values. It could have been interesting to see how the measurements changed over time, and whether this was a good indicator of how a long a patient may stay in the hospital.

One future direction involves repeating this kind of project with data from a different hospital; are the conclusions drawn from this dataset universal across different hospitals? Will the results found from this study actually help another hospital improve efficiency? Another direction to take is looking at the actual hospital stay dates themselves: are there some months in which hospital stays are abnormally longer or shorter?