--- 
title: "LengthOfStay"
author: "Eubin Park & Raphaël Adda"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

With the development of technology worldwide, everything from offices to grocery stores has seen a move toward digitization. The case for the healthcare industry has been no different. In recent years, hospitals have adopted new and improved digital health record systems, which has led to a rapid increase in available healthcare data. Such data includes various kinds of information that can span from patient background and demographics to laboratory test results, prescribed medications, and treatment outcomes. It is not difficult to see that, when combined with the tools of data analytics, this kind of data holds immense potential in not only improving patient care and outcomes, but also in streamlining large-scale healthcare operations. 

Some such real-world applications of healthcare data include predictive analytics, in which insights into patient care and potential treatments can be extracted from large amounts of data in order to guide real-world doctors in making the correct decisions for their patients. This has been seen to be extremely useful in the case of patients with complicated medical histories, for whom big data can provide possibly important predictions. Another example is hospital staffing, for which data on hospital traffic can produce efficient schedules for. 

Acknowledging the significance of healthcare data in the field of data analytics, we have chosen to study a healthcare-related dataset for this final project. In particular, the dataset we hhave chosen to study comprises clinical data collected on hundreds of thousands patient stays in a hospital. The data is composed on information regarding patients' medical histories, physiological lab results, as well as the lengths of each individual patients' stay in the hospital. 

The main question we aim to answer at the end of this project is: How is the length of a patient's stay in the hospital related to their medical history and physiological state? 

We hope that the findings of this project will be able to guide hospital managements in correctly anticipating staffing needs and resource allocations according to a patient's medical history and physiological data upon their admission. If this is successful, this will contribute towards bettering hospitals' large-scale operations.
